#!/usr/bin/python

def poiEmails():
    email_list = [
        "kenneth_lay@enron.net",    
        "kenneth_lay@enron.com",
        "klay.enron@enron.com",
        "kenneth.lay@enron.com", 
        "klay@enron.com",
        "layk@enron.com",
        "chairman.ken@enron.com",
        "jeffreyskilling@yahoo.com",
        "jeff_skilling@enron.com",
        "jskilling@enron.com",
        "effrey.skilling@enron.com",
        "skilling@enron.com",
        "jeffrey.k.skilling@enron.com",
        "jeff.skilling@enron.com",
        "kevin_a_howard.enronxgate.enron@enron.net",
        "kevin.howard@enron.com",
        "kevin.howard@enron.net",
        "kevin.howard@gcm.com",
        "michael.krautz@enron.com",
        "scott.yeager@enron.com",
        "syeager@fyi-net.com",
        "scott_yeager@enron.net",
        "syeager@flash.net",
        "joe'.'hirko@enron.com", 
        "joe.hirko@enron.com", 
        "rex.shelby@enron.com", 
        "rex.shelby@enron.nt", 
        "rex_shelby@enron.net",
        "jbrown@enron.com",
        "james.brown@enron.com", 
        "rick.causey@enron.com", 
        "richard.causey@enron.com", 
        "rcausey@enron.com",
        "calger@enron.com",
        "chris.calger@enron.com", 
        "christopher.calger@enron.com", 
        "ccalger@enron.com",
        "tim_despain.enronxgate.enron@enron.net", 
        "tim.despain@enron.com",
        "kevin_hannon@enron.com", 
        "kevin'.'hannon@enron.com", 
        "kevin_hannon@enron.net", 
        "kevin.hannon@enron.com",
        "mkoenig@enron.com", 
        "mark.koenig@enron.com",
        "m..forney@enron.com",
        "ken'.'rice@enron.com", 
        "ken.rice@enron.com",
        "ken_rice@enron.com", 
        "ken_rice@enron.net",
        "paula.rieker@enron.com",
        "prieker@enron.com", 
        "andrew.fastow@enron.com", 
        "lfastow@pdq.net", 
        "andrew.s.fastow@enron.com", 
        "lfastow@pop.pdq.net", 
        "andy.fastow@enron.com",
        "david.w.delainey@enron.com", 
        "delainey.dave@enron.com", 
        "'delainey@enron.com", 
        "david.delainey@enron.com", 
        "'david.delainey'@enron.com", 
        "dave.delainey@enron.com", 
        "delainey'.'david@enron.com",
        "ben.glisan@enron.com", 
        "bglisan@enron.com", 
        "ben_f_glisan@enron.com", 
        "ben'.'glisan@enron.com",
        "jeff.richter@enron.com", 
        "jrichter@nwlink.com",
        "lawrencelawyer@aol.com", 
        "lawyer'.'larry@enron.com", 
        "larry_lawyer@enron.com", 
        "llawyer@enron.com", 
        "larry.lawyer@enron.com", 
        "lawrence.lawyer@enron.com",
        "tbelden@enron.com", 
        "tim.belden@enron.com", 
        "tim_belden@pgn.com", 
        "tbelden@ect.enron.com",
        "michael.kopper@enron.com",
        "dave.duncan@enron.com", 
        "dave.duncan@cipco.org", 
        "duncan.dave@enron.com",
        "ray.bowen@enron.com", 
        "raymond.bowen@enron.com", 
        "'bowen@enron.com",
        "wes.colwell@enron.com",
        "dan.boyle@enron.com",
        "cloehr@enron.com", 
        "chris.loehr@enron.com"]
    
    return email_list


def poiDictByEmails():
    data_dict = {
        "kenneth_lay@enron.net": "LAY KENNETH L",    
        "kenneth_lay@enron.com": "LAY KENNETH L",
        "klay.enron@enron.com": "LAY KENNETH L",
        "kenneth.lay@enron.com": "LAY KENNETH L", 
        "klay@enron.com": "LAY KENNETH L",
        "layk@enron.com": "LAY KENNETH L",
        "chairman.ken@enron.com": "LAY KENNETH L",
        "jeffreyskilling@yahoo.com": "SKILLING JEFFREY K",
        "jeff_skilling@enron.com": "SKILLING JEFFREY K",
        "jskilling@enron.com": "SKILLING JEFFREY K",
        "effrey.skilling@enron.com": "SKILLING JEFFREY K",
        "skilling@enron.com": "SKILLING JEFFREY K",
        "jeffrey.k.skilling@enron.com": "SKILLING JEFFREY K",
        "jeff.skilling@enron.com": "SKILLING JEFFREY K",
        "kevin_a_howard.enronxgate.enron@enron.net": "Howard, Kevin",
        "kevin.howard@enron.com": "Howard, Kevin",
        "kevin.howard@enron.net": "Howard, Kevin",
        "kevin.howard@gcm.com": "Howard, Kevin",
        "michael.krautz@enron.com": "Krautz, Michael",
        "scott.yeager@enron.com": "YEAGER F SCOTT",
        "syeager@fyi-net.com": "YEAGER F SCOTT",
        "scott_yeager@enron.net": "YEAGER F SCOTT",
        "syeager@flash.net": "YEAGER F SCOTT",
        "joe'.'hirko@enron.com": "HIRKO JOSEPH", 
        "joe.hirko@enron.com": "HIRKO JOSEPH", 
        "rex.shelby@enron.com": "SHELBY REX", 
        "rex.shelby@enron.nt": "SHELBY REX", 
        "rex_shelby@enron.net": "SHELBY REX",
        "jbrown@enron.com": "Brown, James",
        "james.brown@enron.com": "Brown, James", 
        "rick.causey@enron.com": "CAUSEY RICHARD A", 
        "richard.causey@enron.com": "CAUSEY RICHARD A", 
        "rcausey@enron.com": "CAUSEY RICHARD A",
        "calger@enron.com": "CALGER CHRISTOPHER F",
        "chris.calger@enron.com": "CALGER CHRISTOPHER F", 
        "christopher.calger@enron.com": "CALGER CHRISTOPHER F", 
        "ccalger@enron.com": "CALGER CHRISTOPHER F",
        "tim_despain.enronxgate.enron@enron.net": "DeSpain, Timothy", 
        "tim.despain@enron.com": "DeSpain, Timothy",
        "kevin_hannon@enron.com": "HANNON KEVIN P", 
        "kevin'.'hannon@enron.com": "HANNON KEVIN P", 
        "kevin_hannon@enron.net": "HANNON KEVIN P", 
        "kevin.hannon@enron.com": "HANNON KEVIN P",
        "mkoenig@enron.com": "KOENIG MARK E", 
        "mark.koenig@enron.com": "KOENIG MARK E",
        "m..forney@enron.com": "Forney, John",
        "ken'.'rice@enron.com": "RICE KENNETH D", 
        "ken.rice@enron.com": "RICE KENNETH D",
        "ken_rice@enron.com": "RICE KENNETH D", 
        "ken_rice@enron.net": "RICE KENNETH D",
        "paula.rieker@enron.com": "RIEKER PAULA H",
        "prieker@enron.com": "RIEKER PAULA H", 
        "andrew.fastow@enron.com": "FASTOW ANDREW S", 
        "lfastow@pdq.net": "Fastow, Lea", 
        "andrew.s.fastow@enron.com": "FASTOW ANDREW S", 
        "lfastow@pop.pdq.net": "Fastow, Lea", 
        "andy.fastow@enron.com": "FASTOW ANDREW S",
        "david.w.delainey@enron.com": "DELAINEY DAVID W", 
        "delainey.dave@enron.com": "DELAINEY DAVID W", 
        "'delainey@enron.com": "DELAINEY DAVID W", 
        "david.delainey@enron.com": "DELAINEY DAVID W", 
        "'david.delainey'@enron.com": "DELAINEY DAVID W", 
        "dave.delainey@enron.com": "DELAINEY DAVID W", 
        "delainey'.'david@enron.com": "DELAINEY DAVID W",
        "ben.glisan@enron.com": "GLISAN JR BEN F", 
        "bglisan@enron.com": "GLISAN JR BEN F", 
        "ben_f_glisan@enron.com": "GLISAN JR BEN F", 
        "ben'.'glisan@enron.com": "GLISAN JR BEN F",
        "jeff.richter@enron.com": "Richter, Jeffrey", 
        "jrichter@nwlink.com": "Richter, Jeffrey",
        "lawrencelawyer@aol.com": "Lawyer, Larry", 
        "lawyer'.'larry@enron.com": "Lawyer, Larry", 
        "larry_lawyer@enron.com": "Lawyer, Larry", 
        "llawyer@enron.com": "Lawyer, Larry", 
        "larry.lawyer@enron.com": "Lawyer, Larry", 
        "lawrence.lawyer@enron.com": "Lawyer, Larry",
        "tbelden@enron.com": "BELDEN TIMOTHY N", 
        "tim.belden@enron.com": "BELDEN TIMOTHY N", 
        "tim_belden@pgn.com": "BELDEN TIMOTHY N", 
        "tbelden@ect.enron.com": "BELDEN TIMOTHY N",
        "michael.kopper@enron.com": "KOPPER MICHAEL J",
        "dave.duncan@enron.com": "Duncan, David", 
        "dave.duncan@cipco.org": "Duncan, David", 
        "duncan.dave@enron.com": "Duncan, David",
        "ray.bowen@enron.com": "BOWEN JR RAYMOND M", 
        "raymond.bowen@enron.com": "BOWEN JR RAYMOND M", 
        "'bowen@enron.com": "BOWEN JR RAYMOND M",
        "wes.colwell@enron.com": "COLWELL WESLEY",
        "dan.boyle@enron.com": "Boyle, Dan",
        "cloehr@enron.com": "Loehr, Christopher", 
        "chris.loehr@enron.com": "Loehr, Christopher"
    }

    return data_dict


def poiDictByNames():
    pickle_path = "poi_dict_by_names.pkl"

    import pickle
    from os.path import isfile
    
    if isfile(pickle_path):
    
        file_handler = open(pickle_path, "r")
        data_dict = pickle.load(file_handler)
        file_handler.close()

    else:
        
        data_dict = {}
        
        for (k, v) in poiDicByEmails().items():
            if v not in data_dict: # use name as key this time
                data_dict[v] = []
            if k not in data_dict[v]: # build a list of emails for this name
                data_dict[v].append(k)
                
        pickle.dump(data_dict, open(pickle_path, "w"))
    
    return data_dict
